# Generated by Django 5.0 on 2025-10-01 11:43

import django.db.models.deletion
import lib.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.FloatField(validators=[lib.utils.MinValueValidator(0.0)]),
                ),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MenuItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_id",
                    models.ManyToManyField(
                        related_name="menu_items", to="catalogs.category"
                    ),
                ),
                (
                    "menu_item_id",
                    models.ManyToManyField(
                        related_name="categories", to="catalogs.menuitem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "menu_item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalogs.menuitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_delta",
                    models.FloatField(
                        default=0.0, validators=[lib.utils.MinValueValidator(0.0)]
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "menu_item_id",
                    models.ManyToManyField(
                        related_name="item_options", to="catalogs.menuitem"
                    ),
                ),
                (
                    "option_id",
                    models.ManyToManyField(
                        blank=True, related_name="item_options", to="catalogs.option"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="restaurant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="catalogs.restaurant",
            ),
        ),
    ]
