# Generated by Django 5.0 on 2025-10-01 11:43

import django.db.models.deletion
import lib.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            lib.utils.MinValueValidator(0),
                            lib.utils.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                (
                    "total_price",
                    models.FloatField(validators=[lib.utils.MinValueValidator(0.0)]),
                ),
                (
                    "subTotal_price",
                    models.FloatField(validators=[lib.utils.MinValueValidator(0.0)]),
                ),
                (
                    "discount_total",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            lib.utils.MinValueValidator(0.0),
                            lib.utils.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="commerces.address",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="commerces.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_item_name", models.CharField(max_length=100)),
                (
                    "menu_item_price",
                    models.FloatField(validators=[lib.utils.MinValueValidator(0.0)]),
                ),
                (
                    "quantity",
                    models.IntegerField(validators=[lib.utils.MinValueValidator(1)]),
                ),
                (
                    "line_total",
                    models.FloatField(validators=[lib.utils.MinValueValidator(0.0)]),
                ),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="catalogs.menuitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item_options",
                        to="catalogs.option",
                    ),
                ),
                (
                    "order_item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_options",
                        to="commerces.orderitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.ManyToManyField(
                        related_name="order_promos", to="commerces.order"
                    ),
                ),
                (
                    "promo_id",
                    models.ManyToManyField(
                        related_name="order_promos", to="commerces.promo"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="address",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="commerces.user",
            ),
        ),
    ]
